### ISSUE TITLE
About herring

### ISSUE THREAD

**Issue by knutwaagan** [FrankGuldstrand/historical_recipes#5]
Great work on the ingredients, @FrankGuldstrand. Maybe it should specify _small_ herrings?

What do you think?

**Comment by torehof** [comment]
Small _red_ herring?

**Comment by knutwaagan** [comment]
Yes, there clearly isn't enough confusion already!

**Comment by FrankGuldstrand** [comment]
@knutwaagan, @torehof , enig!

@annesbe kan du fixa detta?

**Comment by annesbe** [comment]
Done and done
