### ISSUE TITLE
Vi bør også bruke markdown!

### ISSUE THREAD

**Issue by torehof** [FrankGuldstrand/historical_recipes#6]
Hei,
markdown er skikkelig i vinden. Om vi skal henge med på trendene bør vi også oppdatere.

Hva tenker dere?

hilsen
Tore

**Comment by knutwaagan** [comment]
Jepp. Markdown er fremtiden.

**Comment by torehof** [comment]
Da virker det som problemet er løst. Godt jobba!

**Comment by FrankGuldstrand** [comment]
@torehof enig, Vi må vara med i framkant med disse tingen. Jag ser @torehof er med på båten. Jag kopplar på vår markdownexpert Anne.

@annesbe, kirrar du biffen?
